#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║                     Nginx Reverse Proxy Installer                            ║
# ║                     SoC-in-a-Box Component                                  ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
# Configures Nginx as reverse proxy for SOC services
# Required env vars: SERVER_DOMAIN, ENABLE_TLS, LETSENCRYPT_EMAIL

set -euo pipefail

if ! declare -f info &>/dev/null; then
    info()  { echo "[INFO] $*"; }
    warn()  { echo "[WARN] $*"; }
    error() { echo "[ERROR] $*"; }
fi

run_cmd() {
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        info "[DRY-RUN] Would execute: $*"
        return 0
    fi
    "$@"
}

# ──────────────────────────────────────────────────────────────────────────────
# Installation
# ──────────────────────────────────────────────────────────────────────────────
install_nginx_debian() {
    info "Installing Nginx (Debian/Ubuntu)..."
    
    run_cmd apt-get update
    run_cmd apt-get install -y nginx
    
    if [[ "${ENABLE_TLS:-false}" == "true" ]]; then
        run_cmd apt-get install -y certbot python3-certbot-nginx
    fi
}

install_nginx_rhel() {
    info "Installing Nginx (RHEL/CentOS)..."
    
    run_cmd yum install -y nginx
    
    if [[ "${ENABLE_TLS:-false}" == "true" ]]; then
        run_cmd yum install -y certbot python3-certbot-nginx
    fi
}

# ──────────────────────────────────────────────────────────────────────────────
# Configuration
# ──────────────────────────────────────────────────────────────────────────────
create_config() {
    info "Creating Nginx configuration..."
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        info "[DRY-RUN] Would create Nginx config"
        return 0
    fi
    
    local domain="${SERVER_DOMAIN:-${SERVER_HOSTNAME:-soc.local}}"
    local config_file="/etc/nginx/sites-available/soc-proxy"
    
    # Create sites-available if it doesn't exist (RHEL)
    mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled
    
    cat > "$config_file" << 'EOF'
# SoC-in-a-Box Reverse Proxy Configuration
# Generated by Ghost Tech Security Solutions

upstream wazuh_dashboard {
    server 127.0.0.1:5601;
}

upstream wazuh_api {
    server 127.0.0.1:55000;
}

# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name DOMAIN_PLACEHOLDER;
    
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }
    
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name DOMAIN_PLACEHOLDER;
    
    # SSL Configuration (will be managed by certbot)
    ssl_certificate /etc/nginx/ssl/soc.crt;
    ssl_certificate_key /etc/nginx/ssl/soc.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    
    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    
    # Logging
    access_log /var/log/nginx/soc-access.log;
    error_log /var/log/nginx/soc-error.log;
    
    # Wazuh Dashboard
    location / {
        proxy_pass https://wazuh_dashboard;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_ssl_verify off;
        proxy_read_timeout 90;
        proxy_connect_timeout 90;
    }
    
    # Wazuh API
    location /api/ {
        proxy_pass https://wazuh_api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_ssl_verify off;
    }
    
    # Zabbix (handled by Apache, proxy to it)
    location /zabbix {
        proxy_pass http://127.0.0.1:8080/zabbix;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
EOF
    
    # Replace domain placeholder
    sed -i "s|DOMAIN_PLACEHOLDER|${domain}|g" "$config_file"
    
    info "Configuration created"
}

create_self_signed_cert() {
    info "Creating self-signed SSL certificate..."
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        info "[DRY-RUN] Would create self-signed certificate"
        return 0
    fi
    
    local domain="${SERVER_DOMAIN:-${SERVER_HOSTNAME:-soc.local}}"
    local ssl_dir="/etc/nginx/ssl"
    
    mkdir -p "$ssl_dir"
    
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout "${ssl_dir}/soc.key" \
        -out "${ssl_dir}/soc.crt" \
        -subj "/C=US/ST=State/L=City/O=Ghost Tech/CN=${domain}"
    
    chmod 600 "${ssl_dir}/soc.key"
    
    info "Self-signed certificate created"
}

obtain_letsencrypt() {
    if [[ "${ENABLE_TLS:-false}" != "true" ]]; then
        return 0
    fi
    
    if [[ -z "${LETSENCRYPT_EMAIL:-}" || -z "${SERVER_DOMAIN:-}" ]]; then
        warn "Let's Encrypt requires LETSENCRYPT_EMAIL and SERVER_DOMAIN"
        return 0
    fi
    
    info "Obtaining Let's Encrypt certificate..."
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        info "[DRY-RUN] Would obtain Let's Encrypt certificate"
        return 0
    fi
    
    certbot --nginx -d "${SERVER_DOMAIN}" --email "${LETSENCRYPT_EMAIL}" --agree-tos --non-interactive || \
        warn "Let's Encrypt certificate failed. Using self-signed certificate."
}

enable_site() {
    info "Enabling Nginx site..."
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        info "[DRY-RUN] Would enable site"
        return 0
    fi
    
    # Enable site
    ln -sf /etc/nginx/sites-available/soc-proxy /etc/nginx/sites-enabled/
    
    # Remove default site
    rm -f /etc/nginx/sites-enabled/default
    
    # Include sites-enabled in main config if not already (for RHEL)
    if ! grep -q "sites-enabled" /etc/nginx/nginx.conf; then
        sed -i '/http {/a \    include /etc/nginx/sites-enabled/*;' /etc/nginx/nginx.conf
    fi
    
    # Test configuration
    nginx -t
    
    info "Site enabled"
}

# ──────────────────────────────────────────────────────────────────────────────
# Service Management
# ──────────────────────────────────────────────────────────────────────────────
enable_service() {
    info "Enabling Nginx service..."
    
    run_cmd systemctl daemon-reload
    run_cmd systemctl enable nginx
    run_cmd systemctl restart nginx
    
    if systemctl is-active --quiet nginx; then
        info "Nginx is running"
    else
        warn "Nginx failed to start"
    fi
}

# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────
main() {
    info "Starting Nginx reverse proxy installation..."
    
    case "${OS_FAMILY:-debian}" in
        debian) install_nginx_debian ;;
        rhel)   install_nginx_rhel ;;
    esac
    
    create_config
    create_self_signed_cert
    enable_site
    obtain_letsencrypt
    enable_service
    
    info "Nginx installation complete"
}

main "$@"
